### ISSUE TITLE
Complete the transaction on StarCoin (with signature)

### ISSUE THREAD

**Issue by zven21** [WeLightProject/web3_move_ex#3]
Complete the transaction on StarCoin (with signature)

## TASK's

- [x] Send a transaction
- [x] Obtain transaction info

**Comment by zven21** [comment]
🙋🏻‍♀️

**Comment by leeduckgo** [comment]
Money: `500 xUSDT`

> https://stcscan.io/main/transactions/detail/0x28b027fb572d518c7273e9cb2caee570a2b3edb1e9f70e4662d20a6cfe9f30d1

**Comment by leeduckgo** [comment]
> Dependencies excluded from the package (only Hex packages can be dependencies): bcs

BCS Should be published to hex first so this SDK can be publish

**Comment by zven21** [comment]
> > Dependencies excluded from the package (only Hex packages can be dependencies): bcs
> 
> BCS Should be published to hex first so this SDK can be publish

updated
